### ISSUE TITLE
Update of app 1.0 not work

### ISSUE THREAD

**Issue by Chuck3CZ** [getumbrel/umbrel-bitcoin#32]
RPI 5, NVME 2TB, umbrelOS 1.4.2, app says not running

![Image](https://github.com/user-attachments/assets/d30d9a73-5090-4b01-9d6c-100ce9bf6696)

restoring defaults button says: Failed to restore defaults: EACCES: permission denied, open '/data/app/settings.json.1750869861154.tmp' 

I'll send log if it is needed

**Comment by Chuck3CZ** [comment]
Fixed with patch 1

**Comment by martinbarilik** [comment]
> Fixed with patch 1

it is not, i have just doenloaded it manually and the problem persists.

**Comment by martinbarilik** [comment]
not for me, downloaded it manually, the problem persists

**Comment by Chuck3CZ** [comment]
> not for me, downloaded it manually, the problem persists

You running now two of bitcoin containers, you have to stop one...

**Comment by martinbarilik** [comment]
Can container be running if i do not see him under sudo docker ps -a? :) i don't think so ...
